/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by '江望平' at '17-6-1 下午3:32' with Gradle 2.14.1
 *
 * @author 江望平, @date 17-6-1 下午3:32
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
